export const movieNames: string[] = [
  'Avenger Age of Ultron',
  'Avenger Endgame',
  'Doctor Strange',
  'Iron Man 2',
  'Iron Man 3',
  'Captain Marvel',
  'Black Widow',
  'Transformer Rise of the Beast',
  'Thor Ragnarok',
  'Thor Love and Thunder',
  'Spiderman Homecoming',
  'Guardians of the Galaxy',
  'Avengers Civil War',
  'Black Panther',
  'Thor The Dark World',
  'Avenger Infinity War',
  'Avenger Endgame',
  'Transformer Revenge has Fallen',
  'Transformer Dark of the Moon',
];

export const movieImages: string[] = [
  './Assets/Movies/avenger age of ultron.jpg',
  './Assets/Movies/avenger age of ultron.jpg',
  './Assets/Movies/doctor strange.jpg',
  './Assets/Movies/iron man 2.jpg',
  './Assets/Movies/iron man 3.jpg',
  './Assets/Movies/captain marvel.jpg',
  './Assets/Movies/black widow.jpg',
  './Assets/Movies/transformer rise of beast.jpg',
  './Assets/Movies/thor ragnarok.jpg',
  './Assets/Movies/thor love and thunder.jpg',
  './Assets/Movies/spiderman homecoming.jpg',
  './Assets/Movies/guardians of the galaxy.jpg',
  './Assets/Movies/civil war.jpg',
  './Assets/Movies/black panther.jpg',
  './Assets/Movies/thor the dark world.jpg',
  './Assets/Movies/avengers infinity war.jpg',
  './Assets/Movies/transformer revenge has fallen.jpg',
  './Assets/Movies/dark of the moon.jpg',
];

export const movieDescriptions: string[] = [
  'Earth  mightiest heroes face an AI threat.',
  'The epic conclusion to the Infinity Saga.',
  'A neurosurgeon becomes the Sorcerer Supreme.',
  'Tony Stark faces new challenges as Iron Man.',
  'Tony Stark faces a vengeful terrorist.',
  'Carol Danvers discovers her superhero identity.',
  'Natasha Romanoff confronts her past.',
  'New Transformers threat on Earth.',
  'Thor imprisoned on the planet Sakaar.',
  'Thor faces a powerful new enemy.',
  'Peter Parker balances life as Spider-Man.',
  'A ragtag team saves the galaxy.',
  'Heroes divide over government oversight.',
  'T Challa returns to Wakanda as king.',
  'Thor battles Malekith in Svartalfheim.',
  'Avengers vs. Thanos in a cosmic showdown.',
  'Autobots vs. Decepticons in a hidden war.',
  'Decepticons return for revenge.',
];

  
  
